spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/Activos_DB}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:jose}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8080}